/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminLotsRouteImport } from './routes/_authenticated/admin/lots'
import { Route as AuthenticatedAdminSlotsRouteImport } from './routes/_authenticated/admin/slots'
import { Route as AuthenticatedAdminReservationsRouteImport } from './routes/_authenticated/admin/reservations'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedReservationsIndexRouteImport } from './routes/_authenticated/reservations.index'
import { Route as AuthenticatedReservationsIdRouteImport } from './routes/_authenticated/reservations.$id'
import { Route as AuthenticatedLotsIdRouteImport } from './routes/_authenticated/lots.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminLotsRoute = AuthenticatedAdminLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSlotsRoute = AuthenticatedAdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReservationsRoute = AuthenticatedAdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedReservationsIndexRoute =
  AuthenticatedReservationsIndexRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservationsIdRoute =
  AuthenticatedReservationsIdRouteImport.update({
    id: '/reservations/$id',
    path: '/reservations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLotsIdRoute = AuthenticatedLotsIdRouteImport.update({
  id: '/lots/$id',
  path: '/lots/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/lots': typeof AuthenticatedAdminLotsRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lots/$id': typeof AuthenticatedLotsIdRoute
  '/reservations/$id': typeof AuthenticatedReservationsIdRoute
  '/reservations/': typeof AuthenticatedReservationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/lots': typeof AuthenticatedAdminLotsRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lots/$id': typeof AuthenticatedLotsIdRoute
  '/reservations/$id': typeof AuthenticatedReservationsIdRoute
  '/reservations': typeof AuthenticatedReservationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/lots': typeof AuthenticatedAdminLotsRoute
  '/_authenticated/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/_authenticated/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/lots/$id': typeof AuthenticatedLotsIdRoute
  '/_authenticated/reservations/$id': typeof AuthenticatedReservationsIdRoute
  '/_authenticated/reservations/': typeof AuthenticatedReservationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/vehicles'
    | '/admin'
    | '/admin/lots'
    | '/admin/slots'
    | '/admin/reservations'
    | '/admin/users'
    | '/lots/$id'
    | '/reservations/$id'
    | '/reservations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/vehicles'
    | '/admin'
    | '/admin/lots'
    | '/admin/slots'
    | '/admin/reservations'
    | '/admin/users'
    | '/lots/$id'
    | '/reservations/$id'
    | '/reservations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/vehicles'
    | '/_authenticated/admin'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/lots'
    | '/_authenticated/admin/slots'
    | '/_authenticated/admin/reservations'
    | '/_authenticated/admin/users'
    | '/_authenticated/lots/$id'
    | '/_authenticated/reservations/$id'
    | '/_authenticated/reservations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lots': {
      id: '/_authenticated/admin/lots'
      path: '/lots'
      fullPath: '/admin/lots'
      preLoaderRoute: typeof AuthenticatedAdminLotsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/slots': {
      id: '/_authenticated/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AuthenticatedAdminSlotsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reservations': {
      id: '/_authenticated/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AuthenticatedAdminReservationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/reservations/': {
      id: '/_authenticated/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof AuthenticatedReservationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations/$id': {
      id: '/_authenticated/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof AuthenticatedReservationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lots/$id': {
      id: '/_authenticated/lots/$id'
      path: '/lots/$id'
      fullPath: '/lots/$id'
      preLoaderRoute: typeof AuthenticatedLotsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLotsRoute: typeof AuthenticatedAdminLotsRoute
  AuthenticatedAdminSlotsRoute: typeof AuthenticatedAdminSlotsRoute
  AuthenticatedAdminReservationsRoute: typeof AuthenticatedAdminReservationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminLotsRoute: AuthenticatedAdminLotsRoute,
  AuthenticatedAdminSlotsRoute: AuthenticatedAdminSlotsRoute,
  AuthenticatedAdminReservationsRoute: AuthenticatedAdminReservationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(AuthenticatedAdminRouteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedLotsIdRoute: typeof AuthenticatedLotsIdRoute
  AuthenticatedReservationsIdRoute: typeof AuthenticatedReservationsIdRoute
  AuthenticatedReservationsIndexRoute: typeof AuthenticatedReservationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedLotsIdRoute: AuthenticatedLotsIdRoute,
  AuthenticatedReservationsIdRoute: AuthenticatedReservationsIdRoute,
  AuthenticatedReservationsIndexRoute: AuthenticatedReservationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()